# Generated by Django 3.0.2 on 2020-01-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_api', '0002_auto_20200102_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paradigm',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
